server:
  port: 8080
spring:
  application:
    name: "TicketAvailabilityService"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    active: ${ENV:local}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
aws:
  region: ${AWS_REGION:us-east-1}
adapter:
  dynamodb:
    tickets-table-name: ${TICKETS_TABLE_NAME:tickets}
    orders-table-name: ${ORDERS_TABLE_NAME:orders}
---
spring:
  config:
    activate:
      on-profile: local
aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://dynamodb-local:8000}
